language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
jdk:
- oraclejdk8
branches:
  only:
  - master
  - stable
script:
- ./gradlew clean build
env:
  - HELLO="World"
  global:
  - HELLO="World"
  - secure: urJGasqUKAT0Iu4DNuSN06btyQob84dxM3MYxwiJdPMEayi+scUGig8PVGgYV1ZSzgpthQ2iuIZZ6Z+YMM2RVlhwsJDv889+ScXgY3kk6PxTsgWUkZ9DLjKk5DUv50C5gFu1Ngx02bnk/CVGST67qbLR76vMAEw53TEQ0bbYli8Mkm+VDpfxLQS9JjVHkwrA4EWToWyIb19U/x2ioyXUaLluF3lH3SxPFwDsnvBCPUjIsQV0U64VN4+N866WwRVSeJYM/oDLZO/rWHeKRS7MgoT20xc4aVOKHIEuJDlg13BQ8hKMQ0DLAmlHm+UArs/JF6fJeFC/ECncNtkcede12NohLc/qPaQDz7uFMic0Ul8tFv/bRpAvTEZ3OxzYHwd/EYwpqajzwTuZox0hsX6Ei0crpRj/8Ghmq9lKInTDF77+8KyUKxeqNcGKqUY4EpTUFurxzXDjU6REPsr3Wd+3CXSgmEPTJp3Zc4SOHspV/np8NvD6zzFCG8ZT9UJyLVO8I3pi/mF6yISrg7g1iDZri0YFNwVazgW6DPseNyr4Y5YSLurau3t3TmFM4jYcGsI2+qYRU6HVA0gglcqCxlXVgxzjUn6LfPsrCncUoFiTfnsTYo9Eq4I8SVmj88Wjr5UeW1Xn6HqK3iPVfbtcx/NV6uHbLd25YSMgO5eOvC72BN4=
  - secure: mP31jTkEeGEyD/I/Kp0HGIoJ0aDyki8DzhNvOVdqXub6FVWf6wKmtPNapDSZRKRqaP37+gvDGaGVL9dLV6YkdmVHRURXjaGuHiat5OzVmLWL0SPd5uf4JyjAt9ZO++6gT4HvnSMujVmmXS1M+G0Sk09PP33flc9YQdsXkplPcpn9TFeoIgXMHUgvdyfoAfwl12ed/7LZ9t84pHkdfPeFlDn+HUZNpdHzKp8nJvSVDHaL4MJUE3TQrzhppiPInYNA2ZNS2rx71koXsC6jiWhpi9bNR62V4P9/8oGVQDTP/M1b1XPZS/IdGht3U/m5fTbQdnOyZjxSyOa+3ujkIwCIHyOaxIh9Cx37TrJbzORQ6v5pNrTbQwrOvjUKs7t/3n3wFx2EcZRS9hpXYI1e9sQhDo93DYsGsmw/5Mi7eJPkiCJO42ZLXRUpG2kO92hqLvbVTPxaE/5QoTCuM3b0v2jmPw7XxM/des5gEZz0HOvClObqeT3I4zyyUVhivOCpI3Gq+LC4iQoxVx48jsZV2oH/XpP8vdsfRPj+fR73Zu+bVaJYCNrNJ+kLVXFPdL4yNe7JVWmfhrzv8dt1LE+mUVCit8fRwanRo1d0oVg7ZIfv8+vOwKwPVAnrDqhUktG4icR1kyaUFuk+zCO3XU3S2PQzcyLS42h2UsJLPA1AyQO40Rk=
  - secure: jc1Y6AqNbIWg1ZLd3TjNVRoDaBUoDnUUrYpCqG0IORaQAnpV28n/fTbdAKVqalwlQkT6xt8xzMD3DNg/LNtXVWCwjC5+xEvyT+tIreLkwV+EsPGMVYJWwk34VR1/sdF2ueLjmTq3M+mqM6amanWPiZnQnR9Z+rcJwJzbive61wjn+iufBrd6SWclu4B8PmbQvZkzL08VMDXYDWAZeHa/ArRpmN6WZ+FuaJ3P+uF46Up0ogNhQ0/UYRVUo9FBVJxWjirhluDRz9zA2PcY8SMkOeAN+yRXsyLcIJgfqXMOmYjrasieG+SvpCgSPgv8Z44aBIlWiMIfN9F0gnjrP4pQHcuy14vgab6dFXXN8d0QkOtQ4eNlsWJsIjV3xVoWD3lk4bCH0qTqiIxcgVpxbqt6Z9cKCz7VCq87vEiEnhmQyx0kQJRqMZBpy4E4u8/g1g6Rw7rkbXuxb8/Xwd586iKhgtXxAO6jNbL/72r9AIh29pgd4+Exae9E5IlZN0LucgObdowhgNFKhRzmbyQo2Z2tF5xibYQMmdqrYxO8z+V/WE7BaCK4jkI240ApB0TyWIBMCmvWDdGOQ7Pn2QrtmoSMtEL2UHQ1D9LsIv0ZLxVck4SPcjcQ1ePlmsiW7uethqGetEdMWJHcIY37H2lZ8zSO4Cl4aIzjPd23x31uBtR7OBw=
  - secure: PvTyp0GyOgAzTM6tccLrUJHALrLkBJRDI3nQ9yeJemgcJAZ8WHFgFAwU0RYsxLnRq3VdYbAYCgAS2U49XqftvoEvcZOOJIVuFGEXXPo5/ceDcTRpO2SGJ0RALzT8JzALWD/c+/raPvQxLn89bmJW2dKytXimkiRSu9uJFaDxEsVPTxO+XevV9gdRf4fYHobGqKEQAnn1cadJVP+KUH37AGJKlCVCkX1LwHVeSq4CSod9pHQJJPcJ5RheU0YTMcN5PTTFTl3c4cPcCNDNlVzeXS+wuxqhQnNd7YewAXMk0eSLLFl0bodCEaCqr4ghxMWxUh4iF/1i1rHVAdcoxXApjUqtq2g+DzKclVt/u/NPpdWWJpNb5a+yCbMUE0ilEB07Z2XAwaD0ZcqSu/MjNoGNSlOlLC9SvF4m7w8xJAioujuavqA1KjyhQnO+fmS1BI/ibp91uWP62LnRK7goIY5IrQJqIojsUzRbmZFjbeDY0RUNBYRuePzUbhxfnfsvvTm7Oe4xrrlK91kU0cWoC4NKnPigDHb55RzVHa16hEDxXU/TUeO2LdlGYs02zY0ygDx31IBioeCX85G4wH6TN6naUxv3NQBrr5ZsvPRALq9wMX1mTzufvT262RrtC1Z+NY0ZR6pTxWYbWc6dVgks/mLO+sUHgnG921KqNzx4qMvaO+0=
