language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master
  - stable

script:
- ./gradlew clean build

env:
  global:
  - secure: urJGasqUKAT0Iu4DNuSN06btyQob84dxM3MYxwiJdPMEayi+scUGig8PVGgYV1ZSzgpthQ2iuIZZ6Z+YMM2RVlhwsJDv889+ScXgY3kk6PxTsgWUkZ9DLjKk5DUv50C5gFu1Ngx02bnk/CVGST67qbLR76vMAEw53TEQ0bbYli8Mkm+VDpfxLQS9JjVHkwrA4EWToWyIb19U/x2ioyXUaLluF3lH3SxPFwDsnvBCPUjIsQV0U64VN4+N866WwRVSeJYM/oDLZO/rWHeKRS7MgoT20xc4aVOKHIEuJDlg13BQ8hKMQ0DLAmlHm+UArs/JF6fJeFC/ECncNtkcede12NohLc/qPaQDz7uFMic0Ul8tFv/bRpAvTEZ3OxzYHwd/EYwpqajzwTuZox0hsX6Ei0crpRj/8Ghmq9lKInTDF77+8KyUKxeqNcGKqUY4EpTUFurxzXDjU6REPsr3Wd+3CXSgmEPTJp3Zc4SOHspV/np8NvD6zzFCG8ZT9UJyLVO8I3pi/mF6yISrg7g1iDZri0YFNwVazgW6DPseNyr4Y5YSLurau3t3TmFM4jYcGsI2+qYRU6HVA0gglcqCxlXVgxzjUn6LfPsrCncUoFiTfnsTYo9Eq4I8SVmj88Wjr5UeW1Xn6HqK3iPVfbtcx/NV6uHbLd25YSMgO5eOvC72BN4=
  - secure: OHGJ9rCmHLJRp7HDkyllvPhHxr39A+a1U5OQa8djj7+ljeS/ABMrKbjX/1O9qX3Fo20fU2UwgSTqTtP9chElOACTuLgUfFSqOkxW9hwMckQoxBVIj9wvK/nAzmbrjeXTQH+Xfzq6l/1ch7zFuMFHcGFmWvcYoM8vbBzSslfnTqjZzcRHvV0emHKKLgUFX1GGE1KwZ3zjt6ZWUhtjBKzY8hA/Ed4q127iRU8rlaURZxzG9vEdlPszLg8v19Ycb7ssoDH8kr6gSOD7LJz3nTeO9wzVIcKMdjoInnqr65Gm9pqtheep8RLUmI3DWttc8I963ibktsP5cQ9bc6EYg3bI8/Rh3ShSnZJRy9uQuNOxDf/vPauq/dpqL0D6AhNZK7NA6DYkEOV+Sj87LHPraLjpUh2zeo4TmVAWxHytg8U1HkIXy8eAkBS1QZQuTjlGSL09trXI3vXdXkDpp0/85bCHr1zeRU/VGUAZi1F6pEcgbowKusvzbBrmc6zwIg5/hLWHegvWxuMT4+K7xfKBQ076rurd+5kQqqgSbUMQOhIyQPpeYxOxi4PiGFdIZS5QggYqnLBUUi9MT11AAKVWeO+P909hgkoAGJ2ighJ70bwKuqpNvN4cxltsOwaZPyT0HpdVSrgHvelc7jTq4X4y3srZCaOTvaB/FsyTaLANGoM0cDg=
  - secure: jc1Y6AqNbIWg1ZLd3TjNVRoDaBUoDnUUrYpCqG0IORaQAnpV28n/fTbdAKVqalwlQkT6xt8xzMD3DNg/LNtXVWCwjC5+xEvyT+tIreLkwV+EsPGMVYJWwk34VR1/sdF2ueLjmTq3M+mqM6amanWPiZnQnR9Z+rcJwJzbive61wjn+iufBrd6SWclu4B8PmbQvZkzL08VMDXYDWAZeHa/ArRpmN6WZ+FuaJ3P+uF46Up0ogNhQ0/UYRVUo9FBVJxWjirhluDRz9zA2PcY8SMkOeAN+yRXsyLcIJgfqXMOmYjrasieG+SvpCgSPgv8Z44aBIlWiMIfN9F0gnjrP4pQHcuy14vgab6dFXXN8d0QkOtQ4eNlsWJsIjV3xVoWD3lk4bCH0qTqiIxcgVpxbqt6Z9cKCz7VCq87vEiEnhmQyx0kQJRqMZBpy4E4u8/g1g6Rw7rkbXuxb8/Xwd586iKhgtXxAO6jNbL/72r9AIh29pgd4+Exae9E5IlZN0LucgObdowhgNFKhRzmbyQo2Z2tF5xibYQMmdqrYxO8z+V/WE7BaCK4jkI240ApB0TyWIBMCmvWDdGOQ7Pn2QrtmoSMtEL2UHQ1D9LsIv0ZLxVck4SPcjcQ1ePlmsiW7uethqGetEdMWJHcIY37H2lZ8zSO4Cl4aIzjPd23x31uBtR7OBw=
  - secure: PvTyp0GyOgAzTM6tccLrUJHALrLkBJRDI3nQ9yeJemgcJAZ8WHFgFAwU0RYsxLnRq3VdYbAYCgAS2U49XqftvoEvcZOOJIVuFGEXXPo5/ceDcTRpO2SGJ0RALzT8JzALWD/c+/raPvQxLn89bmJW2dKytXimkiRSu9uJFaDxEsVPTxO+XevV9gdRf4fYHobGqKEQAnn1cadJVP+KUH37AGJKlCVCkX1LwHVeSq4CSod9pHQJJPcJ5RheU0YTMcN5PTTFTl3c4cPcCNDNlVzeXS+wuxqhQnNd7YewAXMk0eSLLFl0bodCEaCqr4ghxMWxUh4iF/1i1rHVAdcoxXApjUqtq2g+DzKclVt/u/NPpdWWJpNb5a+yCbMUE0ilEB07Z2XAwaD0ZcqSu/MjNoGNSlOlLC9SvF4m7w8xJAioujuavqA1KjyhQnO+fmS1BI/ibp91uWP62LnRK7goIY5IrQJqIojsUzRbmZFjbeDY0RUNBYRuePzUbhxfnfsvvTm7Oe4xrrlK91kU0cWoC4NKnPigDHb55RzVHa16hEDxXU/TUeO2LdlGYs02zY0ygDx31IBioeCX85G4wH6TN6naUxv3NQBrr5ZsvPRALq9wMX1mTzufvT262RrtC1Z+NY0ZR6pTxWYbWc6dVgks/mLO+sUHgnG921KqNzx4qMvaO+0=
